---
title: "data_scraping"
author: "Luke Kolar"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F, include = F}
# Initial library loading

library(tidyverse)
library(janitor)
library(tidytext)
library(textdata)
library(stringr)
library(rvest)
```

```{r, include = F}
# 'Genius'-specific packages

library(geniusr)
genius_token()

client_access_token <- "A629GZJinyQQJN11vDjRf_3tjx6Dsw5fpH1hdiLZwhpgABHw4yyTpm6nFQj592p8"
```

```{r, include = F}

```

```{r, message = F}
# set lexicon
bing <- get_sentiments("bing")

# scrape album tracklist
tracklist <- get_album_tracklist_search(artist_name = "Daft Punk",
                                        album_name = "Discovery")

tracklist <- tracklist[c(1, 3:4, 7, 9, 13:14),]

# scrape album lyrics
lyrics <- map_df(tracklist$song_lyrics_url, get_lyrics_url)

# counting negative / positive words
sentiment <- lyrics %>%
  unnest_tokens(word, line) %>%
  # remove stop words
  anti_join(stop_words, by = "word") %>%
  # join afinn score
  inner_join(bing, by = "word") %>%
  # count negative / positive words
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

# plotting top contributors
sentiment %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Discovery: Words that contribute the most to positive and negative sentiment",
       x = NULL) +
  coord_flip() +
  theme_minimal()

```

```{r, echo = F}
# [B] Storing values...

# lyric vectors:

One_More_Time.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "One More Time")
Aerodynamic.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Aerodynamic")
Digital_Love.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Digital Love")
H_B_F_S.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Harder, Better, Faster, Stronger")
Crescendolls.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Crescendolls")
Nightvision.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Nightvision")
Superheroes.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Superheroes")
High_Life.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "High Life")
Something_About_Us.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Something About Us")
Voyager.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Voyager")
Veridis_Quo.lyrics <- get_lyrics_search(artist_name = "Daft Punk",
                  song_title = "Veridis Quo")


# All songs, for use later...

tracklist <- c("One More Time", "Aerodynamic", "Digital Love",
               "Harder, Better, Faster, Stronger", "Crescendolls",
               "Nightvision", "Superheroes", "High Life", 
               "Something About Us", "Voyager", "Veridis Quo",
               "Short Circuit", "Face to Face", "Too Long")
samples.tab <- tibble(tracks = as.vector(tracklist))

# no longer need these:

One_More_Time.url <- "https://www.whosampled.com/Daft-Punk/One-More-Time/"
Aerodynamic.url <- "https://www.whosampled.com/Daft-Punk/Aerodynamic/"
Digital_Love.url <- "https://www.whosampled.com/Daft-Punk/Digital-Love/"
H_B_F_S.url <- "https://www.whosampled.com/Daft-Punk/Harder,-Better,-Faster,-Stronger/"
Crescendolls.url <- "https://www.whosampled.com/Daft-Punk/Crescendolls/"
Nightvision.url <- "https://www.whosampled.com/Daft-Punk/Nightvision/"
Superheroes.url <- "https://www.whosampled.com/Daft-Punk/Superheroes/"
High_Life.url <- "https://www.whosampled.com/Daft-Punk/High-Life/"
Something_About_Us.url <- "https://www.whosampled.com/Daft-Punk/Something-About-Us/"
Voyager.url <- "https://www.whosampled.com/Daft-Punk/Voyager/"
Veridis_Quo.url <- "https://www.whosampled.com/Daft-Punk/Veridis-Quo/"
Short_Circuit.url <- "https://www.whosampled.com/Daft-Punk/Short-Circuit/"
Face_to_Face.url <- "https://www.whosampled.com/Daft-Punk/Face-to-Face/"
Too_Long.url <- "https://www.whosampled.com/Daft-Punk/Too-Long/"

# section header values (for functions in [C]):

samps.txt <- "Contains samples of"
sampd.txt <- "Was sampled in"
cov.txt <- "Was covered in"
rem.txt <- "Was remixed in"

```


```{r, echo = F} 
# [C]: Functions...

shnum.rename <- function(shnum, sh1, sh2, sh3, sh4){
  if(shnum == 4){
    sh.samps <- sh1
    sh.sampd <- sh2
    sh.cov <- sh3
    sh.rem <- sh4
  }else{
    if(shnum == 3){
      if(startsWith(sh1, samps.txt)){
          sh.samps <- sh1
          if(startsWith(sh2, sampd.txt)){
            sh.sampd <- sh2
            if(startsWith(sh3, cov.txt)){
              sh.cov <- sh3
              sh.rem <- NA
            }else{
              sh.cov <- NA
              sh.rem <- sh3
            }
          }else{
            sh.sampd <- NA
            sh.cov <- sh2
            sh.rem <- sh3
          }
        }else{
          sh.samps <- NA
          sh.sampd <- sh1
          sh.cov <- sh2
          sh.rem <- sh3
        }
    }else{
      if(shnum == 2){
        if(startsWith(sh1, samps.txt)){
            sh.samps <- sh1
            if(startsWith(sh2, sampd.txt)){
              sh.sampd <- sh2
              sh.cov <- NA
              sh.rem <- NA
            }else{
              if(startsWith(sh2, cov.txt)){
                sh.sampd <- NA
                sh.cov <- sh2
                sh.rem <- NA
              }else{
                sh.sampd <- NA
                sh.cov <- NA
                sh.rem <- sh2
              }
            }
          }else{
            if(startsWith(sh1, sampd.txt)){
              sh.samps <- NA
              sh.sampd <- sh1
              if(startsWith(sh2, cov.txt)){
                sh.cov <- sh2
                sh.rem <- NA
              }else{
                sh.cov <- NA
                sh.rem <- sh2
              }
            }else{
              sh.samps <- NA
              sh.sampd <- NA
              sh.cov <- sh1
              sh.rem <- sh2
            }
          }
      }else{
        if(shnum == 1){
          if(startsWith(sh1, samps.txt)){
                sh.samps <- sh1
                sh.sampd <- NA
                sh.cov <- NA
                sh.rem <- NA
              }else{
                if(startsWith(sh1, sampd.txt)){
                  sh.samps <- NA
                  sh.sampd <- sh1
                  sh.cov <- NA
                  sh.rem <- NA
                }else{
                  if(startsWith(sh1, cov.txt)){
                    sh.samps <- NA
                    sh.sampd <- NA
                    sh.cov <- sh1
                    sh.rem <- NA
                  }else{
                    sh.samps <- NA
                    sh.sampd <- NA
                    sh.cov <- NA
                    sh.rem <- sh1
                  }
                }  
              }
        }else{
            sh.samps <- NA
            sh.sampd <- NA
            sh.cov <- NA
            sh.rem <- NA
        }
      }
    }
  }
  sh.vect <- as.vector(c(sh.samps, sh.sampd, sh.cov, sh.rem))
  sh.vect
}

all.sh <- function(url){
  headers <- html_text(html_nodes(read_html(url),'.section-header-title'))
  l <- length(headers)
  if(l == 0){
    shnum <- 0
    sh1 <- "No samples"
  }else{
    if(l == 1){
      shnum <- 1
      sh1 <- headers[[1]]
      sh2 <- NA
      sh3 <- NA
      sh4 <- NA
    }else{
      if(l == 2){
        shnum <- 2
        sh1 <- headers[[1]]
        sh2 <- headers[[2]]
        sh3 <- NA
        sh4 <- NA
      }else{
        if(l == 3){
          shnum <- 3
          sh1 <- headers[[1]]
          sh2 <- headers[[2]]
          sh3 <- headers[[3]]
          sh4 <- NA
        }else{
          shnum <- 4
          sh1 <- headers[[1]]
          sh2 <- headers[[2]]
          sh3 <- headers[[3]]
          sh4 <- headers[[4]]
        }
      }
    }
  }
  shnum.rename(shnum, sh1 = sh1, sh2 = sh2, sh3 = sh3, sh4 = sh4)
}

numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
}

samp.tibble <- function(artist, song){
  url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T), "/")
  samp.vect <- all.sh(url)
  samp.tibble <- tibble(type = c("Samples", "Sampled", "Covers", "Remixes"),
                        number = as.numeric(numextract(samp.vect)))
  samp.tibble
}

get.samps <- function(artist, song){
  samp.tib <- samp.tibble(artist, song)
  samp.tib <- samp.tib %>% replace_na(list(number = 0))
  url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T))
  if(pull(samp.tib[1, 2]) == 0){
    samps <- NA
  }else{ 
    if(pull(samp.tib[1, 2]) <= 5){
      n <- pull(samp.tib[1, 2])
      samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url),'.playIcon')))[1:n], 
                      artist = as.vector(html_text(html_nodes(read_html(url),'.trackArtist')))[1:n])
    }else{
      if(ceiling(pull(samp.tib[1, 2]) / 16) == 1){
        url1 <- paste0(url, "/samples/", "?cp=", "1")
        samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                        artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
      }else{
        if(ceiling(pull(samp.tib[1, 2]) / 16) == 2){
          url1 <- paste0(url, "/samples/", "?cp=", "1")
          samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                          artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
          url2 <- paste0(url, "/samples/", "?cp=", "2")
          samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                          artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
        }else{
          if(ceiling(pull(samp.tib[1, 2]) / 16) == 3){
            url1 <- paste0(url, "/samples/", "?cp=", "1")
            samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                            artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))  
            url2 <- paste0(url, "/samples/", "?cp=", "2")
            samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
            url3 <- paste0(url, "/samples/", "?cp=", "3")
            samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
          }else{
            if(ceiling(pull(samp.tib[1, 2]) / 16) == 4){
              url1 <- paste0(url, "/samples/", "?cp=", "1")
              samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                              artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
              url2 <- paste0(url, "/samples/", "?cp=", "2")
              samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
              url3 <- paste0(url, "/samples/", "?cp=", "3")
              samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
              url4 <- paste0(url, "/samples/", "?cp=", "4")
              samps <- add_row(samps, track = as.vector(html_text(html_nodes(read_html(url4),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url4),'.trackArtist'))))
            }else{
              print("more than 4 pages...")
            }
          }
        }
      }
    }
  }
  samps
}

get.sampd <- function(artist, song){
  samp.tib <- samp.tibble(artist, song)
  samp.tib <- samp.tib %>% replace_na(list(number = 0))
  url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T))
  if(pull(samp.tib[2, 2]) == 0){
    sampd <- NA
  }else{ 
    if(pull(samp.tib[2, 2]) <= 5){
      n <- pull(samp.tib[2, 2])
      sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url),'.playIcon')))[1:n], 
                      artist = as.vector(html_text(html_nodes(read_html(url),'.trackArtist')))[1:n])
    }else{
      if(ceiling(pull(samp.tib[2, 2]) / 16) == 1){
        url1 <- paste0(url, "/sampled/", "?cp=", "1")
        sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                        artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
      }else{
        if(ceiling(pull(samp.tib[2, 2]) / 16) == 2){
          url1 <- paste0(url, "/sampled/", "?cp=", "1")
          sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                          artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
          url2 <- paste0(url, "/sampled/", "?cp=", "2")
          sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                          artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
        }else{
          if(ceiling(pull(samp.tib[2, 2]) / 16) == 3){
            url1 <- paste0(url, "/sampled/", "?cp=", "1")
            sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                            artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))  
            url2 <- paste0(url, "/sampled/", "?cp=", "2")
            sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
            url3 <- paste0(url, "/sampled/", "?cp=", "3")
            sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
          }else{
            if(ceiling(pull(samp.tib[2, 2]) / 16) == 4){
              url1 <- paste0(url, "/sampled/", "?cp=", "1")
              sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                              artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
              url2 <- paste0(url, "/sampled/", "?cp=", "2")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
              url3 <- paste0(url, "/sampled/", "?cp=", "3")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
              url4 <- paste0(url, "/sampled/", "?cp=", "4")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url4),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url4),'.trackArtist'))))
            }else{
              print("more than 4 pages...")
            }
          }
        }
      }
    }
  }
  sampd
}

```

```{r}
samp.tibble(artist = "Daft Punk", song = "One More Time")
```


```{r}

get.sampd <- function(artist, song){
  samp.tib <- samp.tibble(artist, song)
  samp.tib <- samp.tib %>% replace_na(list(number = 0))
  url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T))
  if(pull(samp.tib[2, 2]) == 0){
    sampd <- NA
  }else{ 
    if(pull(samp.tib[2, 2]) <= 5){
      n <- pull(samp.tib[2, 2])
      sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url),'.playIcon')))[1:n], 
                      artist = as.vector(html_text(html_nodes(read_html(url),'.trackArtist')))[1:n])
    }else{
      if(ceiling(pull(samp.tib[2, 2]) / 16) == 1){
        url1 <- paste0(url, "/sampled/", "?cp=", "1")
        sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                        artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
      }else{
        if(ceiling(pull(samp.tib[2, 2]) / 16) == 2){
          url1 <- paste0(url, "/sampled/", "?cp=", "1")
          sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                          artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
          url2 <- paste0(url, "/sampled/", "?cp=", "2")
          sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                          artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
        }else{
          if(ceiling(pull(samp.tib[2, 2]) / 16) == 3){
            url1 <- paste0(url, "/sampled/", "?cp=", "1")
            sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                            artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))  
            url2 <- paste0(url, "/sampled/", "?cp=", "2")
            sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
            url3 <- paste0(url, "/sampled/", "?cp=", "3")
            sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                            artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
          }else{
            if(ceiling(pull(samp.tib[2, 2]) / 16) == 4){
              url1 <- paste0(url, "/sampled/", "?cp=", "1")
              sampd <- tibble(track = as.vector(html_text(html_nodes(read_html(url1),'.playIcon'))), 
                              artist = as.vector(html_text(html_nodes(read_html(url1),'.trackArtist'))))
              url2 <- paste0(url, "/sampled/", "?cp=", "2")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url2),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url2),'.trackArtist'))))
              url3 <- paste0(url, "/sampled/", "?cp=", "3")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url3),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url3),'.trackArtist'))))
              url4 <- paste0(url, "/sampled/", "?cp=", "4")
              sampd <- add_row(sampd, track = as.vector(html_text(html_nodes(read_html(url4),'.playIcon'))),
                              artist = as.vector(html_text(html_nodes(read_html(url4),'.trackArtist'))))
            }else{
              print("more than 4 pages...")
            }
          }
        }
      }
    }
  }
  sampd
}

```


```{r}
get.samps(artist = "Daft Punk", song = "One More Time")
get.sampd(artist = "Daft Punk", song = "One More Time")
```

```{r}

url <- One_More_Time.url
n <- pull(samp.tib[1, 2])
samps <- tibble(track = as.vector(html_text(html_nodes(read_html(url),'.playIcon')))[[1:n]], 
                artist = as.vector(html_text(html_nodes(read_html(url),'.trackArtist')))[[1:n]])

samps
```

```{r}
samps.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                    gsub(" ", "-", song, fixed = T))
sampd.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                    gsub(" ", "-", song, fixed = T), "/sampled/", "?cp=", page)
cov.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                    gsub(" ", "-", song, fixed = T), "/covered/", "?cp=", page)
rem.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                    gsub(" ", "-", song, fixed = T))


sampd.rest <- paste0("/sampled/", "?cp=", page)
cov.rest <- paste0("/covered/", "?cp=", page)
rem.rest <- paste0("/remixed/", "?cp=", page)
  
  
  sampd.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T), "/sampled/", "?cp=", page)
  cov.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T), "/covered/", "?cp=", page)
  rem.url <- paste0("https://www.whosampled.com/", gsub(" ", "-", artist, fixed = T),"/", 
                gsub(" ", "-", song, fixed = T), "/remixed/", "?cp=", page)




ceiling(10)
```


